/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.9/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building an application
    application

    `maven-publish`
    signing
    //com.github.ngyewch.git-version
    //`com.palantir.git-version`
}

application {

    // Define the main class for the application
    mainClassName = "App"
}

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    compile("com.google.guava:guava:23.0")

    // Use JUnit test framework
    testCompile("junit:junit:4.12")
}

// In this section you declare where to find the dependencies of your project
repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    
}

tasks.register<Jar>("sourcesJar") {
    from(sourceSets.main.get().allJava)
    archiveClassifier.set("sources")
}

tasks.register<Jar>("javadocJar") {
    from(tasks.javadoc)
    archiveClassifier.set("javadoc")
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            groupId = "io.github.natrem"
            artifactId = "test-gradle-release"
            version = "0.1-SNAPSHOT"

            from(components["java"])
            artifact(tasks["sourcesJar"])
            artifact(tasks["javadocJar"])
 
/*             versionMapping {
                usage("java-api") {
                    fromResolutionOf("runtimeClasspath")
                }
                usage("java-runtime") {
                    fromResolutionResult()
                }
            }*/
        }
    }
    repositories {
        maven {
            val releasesRepoUrl = "https://oss.sonatype.org/service/local/staging/deploy/maven2"
            val snapshotsRepoUrl = "https://oss.sonatype.org/content/repositories/snapshots"
            val isSnapshot = version.toString().endsWith("SNAPSHOT")
            //url = uri( if (isSnapshot) snapshotsRepoUrl else releasesRepoUrl)
			url = uri(snapshotsRepoUrl)
            credentials {
			    //defined in travis project settings or in $HOME/.gradle/gradle.properties
                username = System.getenv("OSSRH_JIRA_USERNAME")
                password = System.getenv("OSSRH_JIRA_PASSWORD")
            }
        }
    }
}

//signing {
//    sign(publishing.publications["mavenJava"])
//}

